version: '3.3'

services:
  mongo:
    image: mongo:4
    ports:
      - '51651:27017'
    volumes:
      - /data/db
    logging:
      driver: "none"
    command: --quiet

  bundlemon:
    build: .
    command: yarn start:watch
    env_file:
      - ./service/dev.env
      - ./service/.env
    environment: 
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - '3333:3333'
    volumes:
      - ./:/app
      - /usr/local/share/.cache/yarn/v6
