name: Build web

on:
  push:
    branches: [master, release/*, next]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build-packages

      - name: Build
        working-directory: ./website
        run: yarn build

      - name: Run bundlemon
        working-directory: ./website
        run: yarn bundlemon
        env:
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}} # important!
