name: Build web

on:
  push:
    branches: [master, release/*, next]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build-packages

      - name: Build
        working-directory: ./website
        run: yarn build

      - name: Run bundlemon
        working-directory: ./website
        run: yarn bundlemon
        env:
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}} # important!
          CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Deploy
        if: ${{ github.ref_name == 'master' }}
        working-directory: ./website
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # https://securitylab.github.com/research/github-actions-untrusted-input/
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: yarn deploy:prod --message "$COMMIT_MSG"
