name: Build web

on:
  push:
    branches: [master, release/*]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build-packages

      - name: Build
        working-directory: ./website
        run: yarn build

      - name: override CI_COMMIT_SHA
        if: github.event_name == 'pull_request'
        run: echo "CI_COMMIT_SHA=${{ github.event.pull_request.head.sha}}" >> $GITHUB_ENV

      - name: Run bundlemon
        working-directory: ./website
        run: yarn bundlemon
        env:
          BUNDLEMON_PROJECT_ID: 60a928cfc1ab380009f5cc0b
