name: Build web

on:
  push:
    branches: [main, release/*, next]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        working-directory: ./apps/website
        run: yarn build

      - name: BundleMon
        working-directory: ./apps/website
        run: yarn bundlemon
        env:
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}} # important!
          CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Deploy
        if: ${{ github.ref_name == 'main' }}
        working-directory: ./apps/website
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # https://securitylab.github.com/research/github-actions-untrusted-input/
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: yarn deploy --prod --message "$COMMIT_MSG"
