name: checks

on:
  push:
    branches: [master, release/*, next]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  packages:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build-packages

      - name: Test
        run: yarn test-packages

      - uses: codecov/codecov-action@v1
        if: ${{ matrix.node-version == '16.x' }} # run this step only one time
        with:
          file: ./coverage/coverage-final.json

      - name: Lint
        if: ${{ matrix.node-version == '16.x' }} # run this step only one time
        run: yarn lint-packages

      - name: Type check
        if: ${{ matrix.node-version == '16.x' }} # run this step only one time
        run: yarn type-check-packages

  website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build-packages

      - name: type check
        working-directory: ./website
        run: yarn type-check

      - name: Lint
        working-directory: ./website
        run: yarn lint

  service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        run: docker-compose -f service/docker-compose.test.yml up -d

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build-packages

      - name: Test
        working-directory: ./service
        run: yarn test

      - uses: codecov/codecov-action@v1
        with:
          file: ./service/coverage/coverage-final.json

      - name: type check
        working-directory: ./service
        run: yarn type-check

      - name: Lint
        working-directory: ./service
        run: yarn lint

      - name: Build
        working-directory: ./service
        run: yarn build
