name: Deploy

on:
  push:
    branches: [master]
  paths:
    - 'website/**'

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build-packages

      - name: Build
        working-directory: ./website
        run: yarn build

      - name: Deploy
        working-directory: ./website
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: yarn deploy:prod --message ${{ github.event.head_commit.message }}
